BEGIN TRANSACTION;
CREATE TABLE BOWERYSCADADEVICESETTINGS (DEVICESETTINGSID NUMERIC(18,0) NOT NULL, FARMCODE varchar(4096) NOT NULL, PRIMARY KEY (DEVICESETTINGSID));
INSERT INTO "BOWERYSCADADEVICESETTINGS" VALUES(11,'F2');
COMMIT;
