BEGIN TRANSACTION;
CREATE TABLE DEVICESETTINGS (
  "DEVICESETTINGS_ID" NUMERIC(18,0) NOT NULL,
  "NAME" VARCHAR(4096) NOT NULL,
  "TYPE" VARCHAR(4096) NOT NULL,
  "DESCRIPTION" VARCHAR(4096) DEFAULT '',
  "ENABLED" BOOLEAN DEFAULT 1,
  CONSTRAINT PK_DEVICESETTINGS PRIMARY KEY (DEVICESETTINGS_ID)
);
INSERT INTO "DEVICESETTINGS" VALUES(11,'Bowery SCADA Simulator','SimulatorDevice','Provides simulated test environment',1);
COMMIT;
