BEGIN TRANSACTION;
CREATE TABLE FINSTCPDEVICESETTINGS (
  "DEVICESETTINGSID" NUMERIC(18,0) NOT NULL,
  "HOSTNAME" VARCHAR(4096) NOT NULL,
  "PORT" INTEGER DEFAULT 9600 NOT NULL,
  "TIMEOUT" NUMERIC(18,0) DEFAULT 2000 NOT NULL,
  "LOCALADDRESS" VARCHAR(4096),
  "SOURCENETWORK" INTEGER DEFAULT 0 NOT NULL,
  "SOURCENODE" INTEGER DEFAULT 0 NOT NULL,
  "SOURCEUNIT" INTEGER DEFAULT 0 NOT NULL,
  "DESTINATIONNETWORK" INTEGER DEFAULT 0 NOT NULL,
  "DESTINATIONNODE" INTEGER DEFAULT 0 NOT NULL,
  "DESTINATIONUNIT" INTEGER DEFAULT 0 NOT NULL,
  "CONCURRENTREQUESTS" INTEGER DEFAULT 2 NOT NULL,
  "MAXREQUESTSIZE" INTEGER DEFAULT 240 NOT NULL,
  "MAXGAPSIZE" INTEGER DEFAULT 0 NOT NULL,
  "WRITEPRIORITYRATIO" INTEGER DEFAULT 5 NOT NULL,
  CONSTRAINT PK_FINSTCPDEVICESETTINGS PRIMARY KEY (DEVICESETTINGSID)
);
INSERT INTO "FINSTCPDEVICESETTINGS" VALUES(1,'omron.com:8888',9600,2000,NULL,0,0,0,0,0,0,2,240,0,5);
COMMIT;
